import React from "react";
import Head from "next/head";
import { Box } from "@gedesurya125/surya-ui";

// External Components
import { UserBar } from "components";

export default function Home() {
  return (
    <Box sx={{}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        as="main"
        sx={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          height: "90vh",
        }}
      >
        <Box
          as="h1"
          sx={{
            fontFamily: "normal",
            fontSize: "4rem",
            "& > a": {
              color: "teal",
            },
          }}
        >
          Welcome to <a href="https://nextjs.org"> My App</a>
        </Box>
        <UserBar />
      </Box>
    </Box>
  );
}
