import { UserBar } from "components";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { UserButton } from "@clerk/nextjs";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ProtectedPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hello From Protected Page</h1>
        <UserBar />
      </main>
    </div>
  );
}
