import { UserBar } from "components";
import Head from "next/head";
import { UserButton } from "@clerk/nextjs";
import { Box, Heading } from "@gedesurya125/surya-ui";

export default function Home() {
  return (
    <Box
      sx={{
        height: "90vh",
      }}
    >
      <Head>
        <title>ProtectedPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        as="main"
        sx={{
          height: "90vh",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <UserButton
          appearance={{
            elements: {
              rootBox: {
                width: "10rem",
              },
              userButtonBox: {
                width: "100%",
              },
              userButtonTrigger: {
                width: "100%",
              },
              userButtonAvatarBox: {
                width: "100%",
                height: "100%",
              },
            },
          }}
        />
        <Heading
          as="h1"
          sx={{
            fontSize: "4rem",
            mt: "1rem",
            fontFamily: "normal",
          }}
        >
          Hello From Protected Page
        </Heading>
        <UserBar />
      </Box>
    </Box>
  );
}
